listen_address: :8080

api:
  domain: https://localhost:8080
  signing_secret: "Cv2UGHgSLdkIpw8"

database:
  mongodb:
    connection_uri: mongodb+srv://akinbezatoglu:7XPincbb@survey.9zncp.mongodb.net/test
    database_name: SurveyDB